version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      SECRET: ${SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      REDIS_URL: redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

# Uncomment this service to run Postgres locally
# db:
#   image: postgres:15-alpine
#   restart: always
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: example
#     POSTGRES_DB: ecommercedb
#   volumes:
#     - pgdata:/var/lib/postgresql/data
#   ports:
#     - "5432:5432"

#volumes:
#  pgdata: